version: '3.7'
services:

  sigma_magento-nginx:
    container_name: sigma_magento-nginx
    volumes:
      - ./magento2:/var/www/html
    build:
      context: ./nginx/
    ports:
      - 8081:80
    restart: always
    environment:
      - PHP_FPM_HOST=sigma_magento-php_fpm
      - PHP_FPM_PORT=9000
    # depends_on:
    #   - sigma_magento-php_fpm

  sigma_magento-php_fpm:
    build:
      context: ./php-fpm/
    container_name: sigma_magento-php_fpm
    volumes:
      - ./magento2:/var/www/html
    restart: always
    # depends_on:
    #   - sigma_magento-data

  sigma_magento_db:
    image: mysql:8.0-debian
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: sigma_magento_db
    environment:
      MYSQL_DATABASE: 'magentodb'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'Qwerty'
      MYSQL_ROOT_PASSWORD: 'test123'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  sigma_magento_elasticsearch:
    image: elasticsearch:7.16.3
    container_name: sigma_magento_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

#  sigma_magento_kibana:
#    container_name: sigma_magento_kibana
#    image: docker.elastic.co/kibana/kibana:7.17.0
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch

volumes:
  my-db:
  elasticsearch-data:
    driver: local
