name: Deploy to Amazon ECS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-west-1                   
  ECR_REPOSITORY: ${{ secrets.REPO_NAME }}           
  ECS_SERVICE: magento-ecs_service                
  ECS_CLUSTER: magento-ecs-cluster                
  ECS_TASK_DEFINITION:  magento_ecs_task_github_task                                         
  CONTAINER_NAME: nginx
  IMAGE_TAG: nginx
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Configure AWS credentials to task definition
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
        role-duration-seconds: 1200
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition  ecs-task-definition --query taskDefinition > ecs-task-definition.json
        
    - name: Render Amazon ECS task definition for first container nginx
      id: render-web-container
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs-task-definition.json
        container-name: magento_ecr_image_nginx
        image: 908410081654.dkr.ecr.eu-west-1.amazonaws.com/magento_ecr_private_rep:nginx
        environment-variables: |
            PHP_FPM_HOST=sigma_magento-php_fpm
            PHP_FPM_PORT=9000
        run: |
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Modify Amazon ECS task definition with second container php
      id: render-app-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs-task-definition.json
        #${{ steps.render-web-container.outputs.task-definition }}
        container-name: sigma_magento-php_fpm
        image: 908410081654.dkr.ecr.eu-west-1.amazonaws.com/magento_ecr_private_rep:php
        run: |
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_PHP"
    
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1 
      with:
        set_repo_policy: true
        task-definition: ${{ steps.render-app-container.outputs.task-definition }}
        service: magento-ecs_service
        cluster: magento-ecs-cluster
        wait-for-service-stability: true
        force-new-deployment: true
