name: Build and push APP to Amazon ECS

on:
 workflow_dispatch:
   inputs:
     AWS_ACCOUNT:
       description: 'AWS ACCOUNT'
       required: true
       type: text
       default: 492457213144
     AWS_REGION:
       description: 'AWS REGION'
       required: true
       type: text
       default: us-east-1
     AWS_SECRET_ACCESS_KEY:
       description: 'AWS_SECRET_ACCESS_KEY'
       required: true
       type: text
     AWS_ACCESS_KEY_ID:
       description: 'AWS_ACCESS_KEY_ID'
       required: true
       type: text
     ECR_REPO:
       description: 'ECR REPOSITORY'
       required: true
       type: choice
       options:
          - nginx
          - aplication
     CONTAINER_NAME_WITH_APP:
       description: 'CONTAINER NAME'
       required: true
       type: text
       default:  sigma_nginx

     
env:
  ECS_TD_JSON_FILE:        ecs-task-definition.json
  DOCKER_IMAGE:            ${{ github.event.inputs.AWS_ACCOUNT }}.dkr.ecr.${{ github.event.inputs.AWS_REGION }}.amazonaws.com/${{ github.event.inputs.ECR_REPO }}:${{ github.sha }}
   
permissions:
  contents: read

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Git clone repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.AWS_REGION }}
        
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: 'Build ${{ github.event.inputs.ECR_REPO }} image'
      run: 
        docker build -f dockerfiles/${{github.event.inputs.CONTAINER_NAME_WITH_APP}}.Dockerfile -t ${{env.DOCKER_IMAGE}} . 
        
    - name: 'push images'
      run: 
        docker login -u AWS -p $(aws ecr get-login --region us-east-1 -m docker login)
        docker build -t public.ecr.aws/o5n0v8g1/nginx:latest .
        docker push public.ecr.aws/o5n0v8g1/nginx:latest
