
name: Deploy to Amazon ECS

on:
 workflow_dispatch:
   inputs:
     AWS_ACCOUNT:
       description: 'AWS account'
       required: true
       type: text
       default: 908410081654
     AWS_REGION:
       description: 'AWS region'
       required: true
       type: text
       default: eu-west-1
     ECR_REPO:
       description: 'ECR repository'
       required: true
       type: choice
       options:
          - common
          - aplication
#      CONTAINER_NAME_NGINX:
#         description: 'Container name first images'
#         required: true
#         type: choice
#         options:
#           - nginx
#           - php
#           - php_magento
     IMAGE_TAG_NGINX:
      description: 'Image tag first images'
      required: true
      type: text
      default: latest
#      CONTAINER_NAME_PHP:
#        description: 'Container name second images'
#        required: true
#        type: choice
#        options:
#           - nginx
#           - php
#           - php_magento
     IMAGE_TAG_PHP:
      description: 'Image tag second images'
      required: true
      type: text
      default:  latest     
     ECS_CLUSTER_NAME:
       description: 'ECS cluster'
       required: true
       type: text
       default:  ecs-prod-0001
     ECS_SERVICE_NAME:
       description: 'ECS service'
       required: true
       type: text
       default:  test2
#      TASK_VERSION:
#        description: 'TASK VERSION'
#        required: true
#        type: text
#        default:  latest
     
env:
  ECS-TASK_DEFENITION-JSON_FILE:             ecs-task-definition.json                                      
   
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy ubuntu
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Git clone repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.AWS_REGION }}
        
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Testing  
      run: echo "${{ github.event.inputs.AWS_ACCOUNT }}.dkr.ecr.${{ github.event.inputs.AWS_REGION }}.amazonaws.com/${{ github.event.inputs.ECR_REPO }}:${{ github.event.inputs.IMAGE_TAG_NGINX }}"
      
#     - name: Render Amazon ECS task definition for first container nginx
#       uses: aws-actions/amazon-ecs-render-task-definition@v1
#       with:
#         task-definition: ${{ env.ECS-TASK_DEFENITION-JSON_FILE }}
#         container-name: ${{ github.event.inputs.IMAGE_TAG_NGINX }}
#         image: ${{ github.event.inputs.AWS_ACCOUNT }}.dkr.ecr.${{ github.event.inputs.AWS_REGION }}.amazonaws.com/${{ github.event.inputs.ECR_REPO }}:${{ github.event.inputs.IMAGE_TAG_NGINX }}
    
    - name: Render Amazon ECS task definition for second container php
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS-TASK_DEFENITION-JSON_FILE }}
        container-name: ${{ github.event.inputs.IMAGE_TAG_PHP }}
        image: ${{ github.event.inputs.AWS_ACCOUNT }}.dkr.ecr.${{ github.event.inputs.AWS_REGION }}.amazonaws.com/${{ github.event.inputs.ECR_REPO }}:${{ github.event.inputs.IMAGE_TAG_PHP }}
        
    - name: Deploy task definition in ECS service
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.AWS_REGION }}
      run: |
       aws ecs stop-task --cluster magento-cluster-CI --task 124ba7b6dc814e85b9930d3b1e579dae
       aws ecs update-service --cluster ${{ github.event.inputs.ECS_CLUSTER_NAME }} --service ${{ github.event.inputs.ECS_SERVICE_NAME }} --task-definition CccomboEXIT:9   --force-new-deployment
